pipeline {
	agent {label 'slave'}
	stages {
		stage('Build') {
			steps {
				sh 'docker build -f Dockerfile . -t muhzii/booster_project:v1.0'
			}
			post {
                    		success {
                         		slackSend(color: '#0000FF', message: "Build for '${env.JOB_NAME}' succeeded. log: (${env.BUILD_URL}console)")
                      		}
                  	}
		}
		stage('Push') {
			steps {
				withCredentials([usernamePassword(credentialsId:"docker", usernameVariable:"USERNAME", passwordVariable:"PASSWORD")]) {
                			sh 'docker login --username $USERNAME --password $PASSWORD'
                			sh 'docker push muhzii/booster_project:v1.0'
                		}
			}
		}
		stage('Deploy') {
			steps {
				sh 'docker run -d -p 8000:8000 muhzii/booster_project:v1.0'
			}
		}
	}
}

